-- Migração Final - Apenas tabelas existentes
SET FOREIGN_KEY_CHECKS=0;

-- USUARIOS
ALTER TABLE usuarios 
    ADD COLUMN IF NOT EXISTS auth_user_id CHAR(36) NULL,
    ADD COLUMN IF NOT EXISTS super_admin TINYINT(1) NOT NULL DEFAULT 0;

-- PLANOS  
ALTER TABLE planos
    ADD COLUMN IF NOT EXISTS qntConexoes BIGINT NULL,
    ADD COLUMN IF NOT EXISTS qntContatos BIGINT NULL,
    ADD COLUMN IF NOT EXISTS qntDisparos BIGINT NULL,
    ADD COLUMN IF NOT EXISTS qntQuadros BIGINT NULL,
    ADD COLUMN IF NOT EXISTS qntAgentesIa BIGINT NULL,
    ADD COLUMN IF NOT EXISTS qntCreditosIa BIGINT NULL,
    ADD COLUMN IF NOT EXISTS menu_ocultar JSON NULL,
    ADD COLUMN IF NOT EXISTS qntUsuarios BIGINT NULL;

-- AGENTES_IA
ALTER TABLE agentes_ia
    ADD COLUMN IF NOT EXISTS conexaoId BIGINT NULL,
    ADD COLUMN IF NOT EXISTS criatividade DECIMAL(3,2) NULL,
    ADD COLUMN IF NOT EXISTS maxCreditos BIGINT NULL,
    ADD COLUMN IF NOT EXISTS conhecimento JSON NULL,
    ADD COLUMN IF NOT EXISTS cor TEXT NULL;

-- CONEXOES
ALTER TABLE conexoes
    ADD COLUMN IF NOT EXISTS instanceName TEXT NULL,
    ADD COLUMN IF NOT EXISTS NomeConexao TEXT NULL,
    ADD COLUMN IF NOT EXISTS Telefone TEXT NULL,
    ADD COLUMN IF NOT EXISTS FotoPerfil TEXT NULL,
    ADD COLUMN IF NOT EXISTS Apikey TEXT NULL,
    ADD COLUMN IF NOT EXISTS contaId CHAR(36) NULL,
    ADD COLUMN IF NOT EXISTS idAgente BIGINT NULL;

-- CONTATOS
ALTER TABLE contatos
    ADD COLUMN IF NOT EXISTS idLista BIGINT NULL,
    ADD COLUMN IF NOT EXISTS variaveis JSON NULL,
    ADD COLUMN IF NOT EXISTS tipo VARCHAR(20) NOT NULL DEFAULT 'contato',
    ADD COLUMN IF NOT EXISTS lid TEXT NULL,
    ADD COLUMN IF NOT EXISTS fotoPerfil TEXT NULL;

-- CONVERSAS
ALTER TABLE conversas
    ADD COLUMN IF NOT EXISTS idAgente BIGINT NULL,
    ADD COLUMN IF NOT EXISTS idConexao BIGINT NULL,
    ADD COLUMN IF NOT EXISTS telefone TEXT NULL,
    ADD COLUMN IF NOT EXISTS pausado TINYINT(1) NULL,
    ADD COLUMN IF NOT EXISTS contatoId BIGINT NULL,
    ADD COLUMN IF NOT EXISTS lida TINYINT(1) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS fotoPerfil TEXT NULL,
    ADD COLUMN IF NOT EXISTS atendente CHAR(36) NULL;

-- MENSAGENS
ALTER TABLE mensagens
    ADD COLUMN IF NOT EXISTS contaId CHAR(36) NULL,
    ADD COLUMN IF NOT EXISTS conexaoId BIGINT NULL,
    ADD COLUMN IF NOT EXISTS mensagem TEXT NULL,
    ADD COLUMN IF NOT EXISTS tipoMensagem VARCHAR(50) NULL,
    ADD COLUMN IF NOT EXISTS arquivoUrl TEXT NULL,
    ADD COLUMN IF NOT EXISTS fromMe TINYINT(1) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS apagada TINYINT(1) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS IA TINYINT(1) NULL;

SET FOREIGN_KEY_CHECKS=1;

SELECT 'Migração concluída!' as status;
